# Generated by Django 5.1.3 on 2024-11-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_item_brand_alter_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(default=0, max_length=100, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
